### ISSUE TITLE
Introducing Ourselves Exercise-Github Setup: repo must be public when using GitKraken free. 

### ISSUE THREAD

**Issue by williamnorfolk** [andreashandel/MADAcourse#10]
Greetings,

When working through the exercise _Introducing Ourselves_ under the Github Setup subheading, second bullet point; students are instructed to create their first repo for the assignment. The instructions read "Choose if you want the repository to be private or public." These instructions are not an issue if the user has installed Gitkraken Pro or has the Student Developer Pack, however when using GitKraken Free students will be unable to access the repo until a public designation has been made.  

Though this would not likely be an issue for any experienced Github/Kraken users, it would be helpful to provide this information for first time users when working on their introductory project. Thanks!

**Comment by andreashandel** [comment]
Thanks, that's a good point. I've been using Gitkraken Pro for so long I forgot that the free version doesn't allow private repositories. I changed the instructions such that it now states it should be a public repo, and also added a comment when I talk about Gitkraken mentioning this limitation of the free version.
