### ISSUE TITLE
Bookdown links not working

### ISSUE THREAD

**Issue by murphyhjohn** [andreashandel/MADAcourse#11]
In resources/resources-course, the current link to Feature Engineering and Selection (FES) isn't working. One alternative link should be http://www.feat.engineering/ but I figured I shouldn't change it yet. UPDATE: All of bookdown is down right now so anything that has a bookmark link isn't working. In resources/resources-general, those are: "Reproducible Medical Research with R" (alt link is https://rmrwr.netlify.app/) and the two bookdown main and archive links.

**Comment by andreashandel** [comment]
if you want, you can go ahead and update broken/non-working links to working ones.

**Comment by andreashandel** [comment]
thanks
