### ISSUE TITLE
just a typo

### ISSUE THREAD

**Issue by yz17970** [andreashandel/MADAcourse#13]
under course communication tab:
"I prefer you use the discussion boards instead of email to ask questions"
--> 
"I prefer you to use the discussion boards instead of email to ask questions"

**Comment by andreashandel** [comment]
Thanks, but I think my way is the right grammar? Anyone else want to comment on which is the right way of saying/writing this?

**Comment by paigeduffin** [comment]
I don't see anything wrong with the way you originally wrote it!

**Comment by askarlupka** [comment]
I believe that technically @yz17970 is right. The verb is supposed to follow "to". Here's an [explanation](https://www.grammarbank.com/would-rather-would-prefer.html). It's down towards the bottom.

**Comment by andreashandel** [comment]
Thanks for all the input. I googled around a bit more, and my latest understanding is that both versions are correct, however some folks recommended the wording "I prefer that you use", which I like and I changed it to that. [See here](https://forum.wordreference.com/threads/prefer-you-have-you-to-have-you-having-a-paypal-account.3087209/)
