### ISSUE TITLE
Minor Typo in "Modules" drop-down menu! 

### ISSUE THREAD

**Issue by paigeduffin** [andreashandel/MADAcourse#14]
Good evening, 

I noticed on the [MADA course GitHub](https://andreashandel.github.io/MADAcourse/index.html) there is a minor typo under the "Modules" tab. More specifically, on the "Modules" drop-down menu, the first module reads "1. Coures and Tools Introduction", but I believe you intended to say "1. **_Course_** and Tools Introduction." 

Respectfully,

Paige Duffin

**Comment by andreashandel** [comment]
Thanks, fixed. Will be updated when I re-post the course.
