### ISSUE TITLE
Frederick_Clarity in Module 5a

### ISSUE THREAD

**Issue by JuliaFrederick** [andreashandel/MADAcourse#15]
In this section you list explicitly for some chapters that we will need to know them for the quiz, other chapters we won't, and some you don't say anything about at all. 
Specifically, Module 5a section "Working with different data types in R." For chapters 25 and 27, there isn't anything said about how much of these we will need to know for the quizzes, and with the amount of reading in the chapters for this module I'd like to know how much focus I should be putting on these as well. 

##Assignment for Module 4
##Julia Frederick

**Comment by andreashandel** [comment]
Thanks. Interesting point and something I have been thinking about too. I'd actually like to move that over to the eLC discussion to get some more feedback. I'll post something there in the teaching section.

**Comment by andreashandel** [comment]
But specifically for the ones you mentioned, I thought the way I wrote indicated that I wouldn't quiz those chapters, but I should have been clearer about them being optional. Rewrote that now.
