### ISSUE TITLE
Issue opening tabs for topics at the top of course site

### ISSUE THREAD

**Issue by mncarmic** [andreashandel/MADAcourse#16]
This could just be an error with my computer/mouse, but whenever I hover over the tabs at the top of the course site, the "subtopics" under that tab don't open. When I try to click on them the subtopics disappear. In order to open them I have to right click on the topic (ie Modules, or exercises), then click on the subtopic I want. Again, could just be an error with my computer.

**Comment by andreashandel** [comment]
Unfortunately I can't reproduce the problem. When I hover over the main tabs, also nothing happens, but when I click on them, the menu opens. Once I move to a specific menu item, the sub-menu opens. Could you maybe post a screenshot or a short screen capture video to show the problem?

**Comment by mncarmic** [comment]
Here is a screenshot of me having to right click to get the sub titles to pop up. I have also discovered hitting the command button or shift button on my Mac will open up the sub topics!
![Screen Shot 2019-09-06 at 2 41 18 PM](https://user-images.githubusercontent.com/54370264/64452635-c76cd580-d0b4-11e9-97cc-7775561b6f1c.png)

**Comment by andreashandel** [comment]
Thanks. I'll see if I can find someone with a Mac and try to reproduce the problem, once I see it I can try to figure out what to do. All this, i.e. the layout and behavior of the website, is controlled by the CSS theme I'm using for the page. A simple (but maybe confusing) choice would be to change the layout. A much harder thing would be for me to try and go in and fix the style/CSS myself. But I'll look into it a bit more.
