### ISSUE TITLE
Prefer video to guide how to do something

### ISSUE THREAD

**Issue by TrangQuach** [andreashandel/MADAcourse#18]
Dear Dr. Handel,

In some modules, you write down some steps to do something such as clone to github by gitkraken, reference management in Markdown, creating introduction page and so on.

I am new to Github and R markdown. Sometimes, the guidance is not step by step to do it. Thus, it took me 3-4 hours to figure out and I am still not sure what I understand is true or not. For example, reference management in Markdown. I prefer to learn through a short video. For example, a video show how to make a citation in R markdown and automatically produce a word document with reference. 

I only have one suggestion to improve this course. Overall, it is good.

**Comment by andreashandel** [comment]
Thanks. I've been contemplating recording some videos, I just wasn't sure if it is worth the effort. Seems like it might help. I'll consider doing so either later in this course or - more likely - a future version of this course. In the meantime, I'm sure there are videos on a lot of those topics already online, if you find some, please post to eLC so others can also use them if they want.
