### ISSUE TITLE
Clarification on advantages of using Gitraken vs RStudio's Git client

### ISSUE THREAD

**Issue by ellenmonster** [andreashandel/MADAcourse#19]
In the first course module, we are encouraged to download a Git client (such as GitRaken) to work with Git repositories. I was wondering if you could provide clarification on the advantages of a Git client such as GitRaken, over using RStudio's basic Git client. I'm asking only because I tried using GitRaken but found it confusing, so I defaulted back to using RStudio's basic Git client. But I feel like I must be 'missing out' on something by using RStudio instead of GitRaken--I just haven't figured out yet what that 'missing out' is. Could you provide some insight on the major advantages of GitRaken over simply using RStudio's Git client?

**Comment by ellenmonster** [comment]
I re-opened this issue to try the 'Assignees' and 'Labels' functions, but I can't seem to use them--can they only be used by the organizer?

**Comment by andreashandel** [comment]
Thanks. Using Git through Rstudio only works for R based projects. If you have a non-R Github project, going through RStudio is not a good way. Also Gitkraken has many advanced features not available through RStudio, features you might want to use at some point. I added some more text to that section of the course to explicitly state that.
And I think only the repository owner and team members can use the labels (though I'm not too familiar with their use myself).
