### ISSUE TITLE
suggestions for MADA course

### ISSUE THREAD

**Issue by meganejlott** [andreashandel/MADAcourse#20]
Hi Dr. Handel, 

Thanks so much for giving this opportunity to provide feedback on the course site. It looks like the site has been combed through and is looking great! I have just a few suggestions and lots of praise to share. 

Is there a way to center in the second line of the University Honor Code on the Syllabus Menu? 

![Syllabus Menu](https://user-images.githubusercontent.com/50665408/64426114-b9e72980-d07b-11e9-9762-25427871c678.JPG)

When working through the Wine ratings exercise, the file would only ever save on my device as a .txt file. Eventually, I copied and pasted the code into a new Rmd file and ran it from there. Not sure if anyone else had a problem with this.

As we create R markdown files for our own notes, I've been hoping to add in notes on functions and other tools in R. How do we go about writing these functions so that they appear with the font and grey background as they do in your site? 

In terms of praise - thank you for making the website to user-friendly and accessible! I'm grateful for your friendly language and clear instructions. Having an online platform, it's some times hard to tell tone. Thank you for including emotions (and emojis!) to help us understand how we should be reading along - for providing a voice to the text.

Thank you!
Megan

**Comment by andreashandel** [comment]
That centering would require me to try and 'hack' the CSS style on which the course is based. Would be a lot of work, so I think I skip that one for now :)

Not sure about the wine file, haven't heard anyone else having a problem (though they might have also had to do it the way you did). I think some browsers by default suggest txt as ending, but you can just change the ending to Rmd.

I'm not sure exactly what you mean by 'writing function so they look like on the site' but in general, you can change the style of the HTML for an Rmd file by settings in the YAML. Take a look at [this section in the R Markdown book](https://bookdown.org/yihui/rmarkdown/html-document.html#appearance-and-style) it might answer your question?
