### ISSUE TITLE
RStudio Clarification

### ISSUE THREAD

**Issue by askarlupka** [andreashandel/MADAcourse#22]
One thing that took me awhile to figure out because I've never used R/RStudio before was the RStudio markdown view. Maybe some clarification on this or a link out would be nice. Specifically, in RStudio in the top left panel where the script is written there is a button that says R Script that can be toggled to different ones such as R Markdown. This was confusing. Then at the same time when in the RMarkdown view the differences between all the different "Run" selections. Such as "Run selected lines, run current chunk..." I'm unsure of which is better to use in different situations, and I've mostly just been using "Run All" because it's been giving me the most reliable results. 
![Screen Shot 2019-09-06 at 2 08 33 PM](https://user-images.githubusercontent.com/54122306/64450319-de5cf900-d0af-11e9-94db-4a2a4b47efde.png)

--

On the website, the header has today's date for every page. I don't know if it's supposed to be the date that it was edited because I know you're changing a lot of stuff, or if it's updating in real time. 

--

This is unrelated to the website...but the discussion board on ELC is horrible. I don't know if it's because I don't know how to use it or what. But I can't view the thread when I'm attempting to reply so it's very irritating to respond to people. It doesn't really foster conversation very well.

**Comment by andreashandel** [comment]
I agree, RStudio can be a bit confusing initially. I've added a section to the R/RStudio document pointing to further resources that help with RStudio. I was actually surprised that I couldn't find more RStudio beginner tutorials, if you found some, I'd love to know and include them.

The date on each site is generated when I re-create the website. Currently the way that works is that every page, no matter if I change it or not, is re-built and as such gets the date of the latest change anywhere on the site. It would be nice to only show the 'last modified' date for the pages that have changed, but I haven't figured out how to do that yet (in a non-manual way).

I agree that eLC is very clunky. I find once you get the hang of it, it's ok, though certainly not what I would call user-friendly. I was contemplating of not using it and instead use a 3rd party app like Slack. I wasn't sure if it was worth learning/using yet another tool. I'd be interested if others also think eLC is so bad we should switch. I'd be willing to do that mid-course, I just don't want this to lead to more confusion and problems than we would benefit.
