### ISSUE TITLE
Identifying important course information

### ISSUE THREAD

**Issue by Rayense** [andreashandel/MADAcourse#23]
Hi Dr. Handel, 

I really appreciated the skills I've been able to pick up in this course so far and I look forward to the rest of the semester. One of the things I've struggled most with in this course so far is knowing where to find all important information and when assignments are due. For example, I've gone by the schedule under General Information but I failed to see that parts of assignments are due are different times under the exercise description. Or an issue shared by several classmates was appropriately participating in class discussions. I know this can be solved by carefully reading all the relevant course information but I wanted to share the thing I was struggling with in navigating the course. 

Thanks, 
Emily

**Comment by andreashandel** [comment]
Thanks. I don't think you actually missed the assignment due dates, all was due Fridays so far. I changed the "Issues" exercise to Wed for next time I teach it but that didn't apply to you. I just added that to the schedule as well. If there are specific ones that are still not in sync, let me know.

I'm not sure what I can improve about class discussions (other than ditching eLC, which I was/am contemplating but not sure if it's worth using yet another tool). Any specific suggestions on how to improve the discussion part? I'm also not quite happy how that part of the course is currently going.
