### ISSUE TITLE
Resource Suggestions for MADA course

### ISSUE THREAD

**Issue by idbachli** [andreashandel/MADAcourse#24]
Hello Dr. Handel!

I watched some of these videos when we were first learning how to code for this class, and I found them to be somewhat informative and helpful. They are youtube videos that just go over how to do some basic stuff in R, and why R is so important. They are nice because you can listen to them while you code, and also watch the examples which in turn helps with coding practice. I think they could be useful to your course at least as a beginner's guide, offering additional support to what you have already provided. 

https://www.youtube.com/watch?v=fDRa82lxzaU

https://www.youtube.com/watch?v=_V8eKsto3Ug

Thanks!

**Comment by andreashandel** [comment]
Thanks. Online videos are a good source. There are a ton out there. Unfortunately I haven't had time to properly review them and to decide which ones specifically to include/mention, but I'll consider listing some in the future in the resources section.
