### ISSUE TITLE
Github Setup Instructions

### ISSUE THREAD

**Issue by meganejlott** [andreashandel/MADAcourse#29]
Hi Dr. Handel! This is a small suggestion, but I keep geeting tripped up with the Github instructions on the introducing Ourselves Page. 

Here's the current text:
"Under the Options tab in settings, scroll down to Github Pages and **switch it to master from none**. Don’t choose a theme." 

Is it possible to change it to "**switch from none to master**". For some reason, I can never read this blurb right and think that "none" is the correct setting. Thinking through it, I see why master works at this stage in the course.

**Comment by andreashandel** [comment]
thanks, i adjusted/rewrote. will show up in the next update for the website.
