### ISSUE TITLE
Link on Website for Tree fitting exercise not working?

### ISSUE THREAD

**Issue by alblubaugh** [andreashandel/MADAcourse#31]
I have tried to follow the link to the next exercise on the website page (https://andreashandel.github.io/MADAcourse/Exercise_Tree_Fitting.html) without luck.

I keep getting the 404 page not found response. I will keep trying to figure it out, as it may be something on my end, but I wanted to mention it just in case.

Amanda

**Comment by williamnorfolk** [comment]
I am receiving the same error as well, so I do not think it is on your end Amanda! Thanks for posting the issue!

**Comment by andreashandel** [comment]
Thanks. I think it's fixed now. Let me know if you notice anything else not working.
